logging:
  level:
    org.springframework.security: DEBUG
security:
  user:
    role: USER,ADMIN
server:
  port: 8082
spring:
# Redis properties
  redis:
   port: 6379
   host: 192.168.99.100
   pool:
     maxIdle: 8 # max idle connections in the pool
     minIdle: 0 # min idle connections in the pool
     maxActive: -1 # no limit to the number of active connections
     maxWait: 30000 # time limit to get a connection - only applies if maxActive is finite